CREATE DATABASE DIARIORELATORIO;

USE DIARIORELATORIO;



CREATE TABLE USUARIO(
  IDUSUARIO INT NOT NULL AUTO_INCREMENT ,

  NOMEIDUSUARIO VARCHAR(45) NOT NULL ,
  PWDUSUARIO VARCHAR(45) NOT NULL ,

  PRIMARY KEY(IDUSUARIO)
);


CREATE TABLE CLIENTE(
  IDCLIENTE INT NOT NULL AUTO_INCREMENT ,
  CODCLIENTE INT NOT NULL,

  NOMECLIENTE VARCHAR(45) NOT NULL ,
  NTELEFONECLIENTE VARCHAR(45),

  PRIMARY KEY(IDCLIENTE)
);


CREATE TABLE TIPODESC(
  IDTIPODESC INT NOT NULL AUTO_INCREMENT ,

  NOMETIPODESC VARCHAR(45) NOT NULL ,

  PRIMARY KEY(IDTIPODESC)
);


CREATE TABLE OPERADORA(
  IDOPERADORA INT NOT NULL AUTO_INCREMENT ,

  NOMEOPERADORA VARCHAR(45) NOT NULL ,

  PRIMARY KEY(IDOPERADORA)
);



CREATE TABLE PMGT(
  IDPMGT INT NOT NULL AUTO_INCREMENT ,

  NOMEPMGT VARCHAR(45) NOT NULL ,
  NPARCELAPMGT INT NOT NULL ,
  DIASPMGT INT NOT NULL ,
  
  PRIMARY KEY(IDPMGT)
);


CREATE TABLE OPERADORAPGMT(
  FKOPERADORA INT NOT NULL,
  FKPMGT INT NOT NULL,

  TAXAOPERADORAPGMT FLOAT NOT NULL ,

 FOREIGN KEY(FKOPERADORA) REFERENCES OPERADORA(IDOPERADORA),
 FOREIGN KEY(FKPMGT) REFERENCES PMGT(IDPMGT)
);


CREATE TABLE DESCR(
  IDDESCR INT NOT NULL AUTO_INCREMENT ,
  FKCLIENTE INT NOT NULL ,
  FKTIPODESC INT NOT NULL ,
  FKUSUARIO INT NOT NULL ,

  VALORDESC VARCHAR(285) NOT NULL ,
  DATEDESC DATE NOT NULL ,
  VALORBRUTODESC FLOAT NOT NULL ,
  DESCTONTODESC FLOAT NOT NULL ,
  VALORREALDESC FLOAT NOT NULL ,
  
  PRIMARY KEY(IDDESCR) ,
  FOREIGN KEY(FKCLIENTE) REFERENCES CLIENTE(IDCLIENTE),
  FOREIGN KEY(FKTIPODESC) REFERENCES TIPODESC(IDTIPODESC),
  FOREIGN KEY(FKUSUARIO) REFERENCES USUARIO(IDUSUARIO)
);



CREATE TABLE ANOTACAO(
  IDANOTACAO INT NOT NULL AUTO_INCREMENT ,
  FKDESC INT NOT NULL,

  NOMEANOTACAO VARCHAR(45) NOT NULL ,
  DESTANOTACAO INT NOT NULL,

 PRIMARY KEY(IDANOTACAO),
 FOREIGN KEY(FKDESC) REFERENCES DESCR(IDDESCR)
);



CREATE TABLE DESCPGMT(
  FKDESC INT NOT NULL,
  FKOPERADORAPGMT INT NOT NULL,

  DTRECEBIMENTO DATE NOT NULL ,
  VLRDESCRICAOPGMT DECIMAL(2) NOT NULL,

 FOREIGN KEY(FKDESC) REFERENCES DESCR(IDDESCR),
 FOREIGN KEY(FKOPERADORAPGMT) REFERENCES OPERADORAPGMT(FKPMGT)
);


-- Partes dos Inserts como Teste
INSERT INTO USUARIO (NOMEIDUSUARIO, PWDUSUARIO) VALUES
('Lucas Ito', PASSWORD('blablabla')),
('Eloa', PASSWORD('blablabla')),
('Meu Pai', PASSWORD('blablabla'));


INSERT INTO CLIENTE (CODCLIENTE, NOMECLIENTE, NTELEFONECLIENTE) VALUES
(1, 'Cliente normal', ''),
(2, 'Zeinaide Jorqueira', '14999999999'),
(3, 'Erica Hashimoto', '14999999999');


INSERT INTO TIPODESC (NOMETIPODESC) VALUES
('Pagou Venda'),
('Deixou em Condicional'),
('Pagou Conta'),
('Marcou'),
('Não Levou');


INSERT INTO OPERADORA (NOMEOPERADORA) VALUES
('Sumup'),
('Mercado Pago'),
('PicPay');


INSERT INTO PMGT (NOMEPMGT, NPARCELAPMGT, DIASPMGT) VALUES
('Pix', 1, 0),
('Débito', 1, 0),
('Crédito 1x - À vista', 1, 30),
('Crédito 2x - Parcelado 2x', 1, 30),
('Crédito 3x - Parcelado 3x', 1, 30),
('Crédito 4x - Parcelado 4x', 1, 30),
('Crédito 5x - Parcelado 5x', 1, 30),
('Crédito 6x - Parcelado 6x', 1, 30),
('Dinheiro', 1, 0);


INSERT INTO OPERADORAPGMT (FKOPERADORA, FKPMGT, TAXAOPERADORAPGMT) VALUES
(1, 2, 2.5), 
(1, 3, 2.5), 
(1, 4, 2.5), 
(1, 5, 2.5), 
(1, 6, 2.5), 
(1, 7, 2.5), 
(1, 8, 2.5), 

(2, 2, 2.5), 
(2, 3, 2.5), 
(2, 4, 2.5), 
(2, 5, 2.5), 
(2, 6, 2.5), 
(2, 7, 2.5), 
(2, 8, 2.5),

(3, 2, 2.5), 
(3, 3, 2.5), 
(3, 4, 2.5), 
(3, 5, 2.5), 
(3, 6, 2.5), 
(3, 7, 2.5), 
(3, 8, 2.5); 

INSERT INTO DESCR (FKCLIENTE, FKTIPODESC, FKUSUARIO, VALORDESC, DATEDESC, VALORBRUTODESC, DESCTONTODESC, VALORREALDESC) VALUES
-- Exemplos de inserção em DESCR, ajuste conforme necessário
(1, 1, 1, 'Descrição do desconto 1', '2023-11-27', 100.00, 10.00, 90.00),
(2, 2, 2, 'Descrição do desconto 2', '2023-11-27', 150.00, 15.00, 135.00),
(3, 3, 3, 'Descrição do desconto 3', '2023-11-27', 120.00, 12.00, 108.00);

-- Inserção de dados em ANOTACAO
INSERT INTO ANOTACAO (FKDESC, NOMEANOTACAO, DESTANOTACAO) VALUES
-- Exemplos de inserção em ANOTACAO, ajuste conforme necessário
(1, 'Anotação importante', 1),
(1, 'Anotação mais ou menos', 2),
(2, 'Anotação 2', 2),
(3, 'Anotação 3', 3);


